#!/usr/bin/env python3
"""Rebuild a cover at print resolution and re-set its bottom line as real type.

The covers were generated by an image model that tops out at 1024x1536, which
is 171 ppi on a 6x9 page. There is no higher-resolution original to re-export,
so the artwork is upscaled — and the one part that upscaling cannot save, the
type, is thrown away and re-set as real type at the new resolution. Leather
grain tolerates interpolation; letterforms do not.

The book icon is never touched.

    python3 tools/cover-rebuild.py --check      # report, write nothing
    python3 tools/cover-rebuild.py              # write the rebuilt covers
"""
import os
import subprocess
import sys

import numpy as np
from PIL import Image, ImageFilter

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.join(HERE, '..')
OUT_W, OUT_H = 1800, 2700

# Each cover: its source, the band holding the line to replace, clean leather
# to rebuild that band from, and the line to set in its place. Coordinates are
# in the 1024x1536 source.
COVERS = [
    dict(name='book',
         src='docs/book/src/cover3e.png',
         out='docs/book/src/cover3e-print.png',
         band=(1418, 1467),          # y range to clear, inclusive-exclusive
         above=(1396, 1418),         # clean leather above
         below=(1470, 1492),         # clean leather below
         cap=24,                     # cap height of the old line, in source px
         baseline=1454,
         ink='book',
         text='THE BOOK · GAP · STREAK'),
    dict(name='guide',
         src='docs/start-here/cover-src.png',
         out='docs/start-here/cover-print.png',
         band=(1410, 1450), above=(1388, 1410), below=(1452, 1474),
         cap=23, baseline=1441,
         ink='guide',
         text='THE BOOK · GAP · STREAK'),
]

# measured off the covers themselves: the book's foil averages RGB 207/177/118,
# the guide's type is a flat deep green on cream
BOOK_INK = ('linear-gradient(180deg,#E8D29C 0%,#D9B46C 52%,#A87B2A 100%)',
            'drop-shadow(0 {a:.2f}px {b:.2f}px rgba(0,30,12,.55)) '
            'drop-shadow(0 -{c:.2f}px 0 rgba(255,245,210,.22))')
GUIDE_INK = ('linear-gradient(180deg,#1B4634 0%,#14372A 100%)',
             'drop-shadow(0 {a:.2f}px {b:.2f}px rgba(120,100,70,.28))')


def gold_mask(a):
    """The book's foil type: warmer and brighter than the leather under it."""
    return ((a[:, :, 0] > 120) & (a[:, :, 1] > 100) & (a[:, :, 2] < 140)
            & (a[:, :, 0] > a[:, :, 2] + 40))


def green_mask(a):
    """The guide's type: deep green on a cream ground."""
    return (a[:, :, 1] > a[:, :, 0] + 6) & (a.sum(2) < 330)


def measure(path, search=(0.88, 0.98), x=(110, 915)):
    """Find the bottom line's band, cap height and baseline in a cover."""
    a = np.asarray(Image.open(os.path.join(ROOT, path)).convert('RGB')).astype(int)
    h = a.shape[0]
    g = gold_mask(a)[int(h * search[0]):int(h * search[1]), x[0]:x[1]]
    rows = np.where(g.sum(1) > 0)[0] + int(h * search[0])
    cols = np.where(g.sum(0) > 0)[0] + x[0]
    if not len(rows):
        return None
    return dict(top=int(rows.min()), bottom=int(rows.max()),
                left=int(cols.min()), right=int(cols.max()),
                cap=int(rows.max() - rows.min() + 1), baseline=int(rows.max()))


def clear_band(img, band, above, below):
    """Rebuild the band from the leather around it, keeping the grain."""
    a = np.asarray(img).astype(np.float32)
    y0, y1 = band
    top = a[above[0]:above[1]]
    bot = a[below[0]:below[1]]
    n = y1 - y0
    for i in range(n):
        t = i / max(n - 1, 1)
        # mirror the clean strips inward so the grain never repeats visibly
        up = top[-1 - (i % len(top))]
        dn = bot[i % len(bot)]
        a[y0 + i] = up * (1 - t) + dn * t
    return Image.fromarray(np.clip(a, 0, 255).astype(np.uint8))


def render_line(text, px_cap, width, height, ink='book'):
    """Set the line as real type, in Chromium, in the cover's own ink."""
    grad, shadow = BOOK_INK if ink == 'book' else GUIDE_INK
    shadow = shadow.format(a=px_cap * 0.055, b=px_cap * 0.07, c=px_cap * 0.028)
    font = os.path.join(ROOT, 'docs', 'book', 'fonts', 'poppins-latin-600-normal.woff2')
    size = round(px_cap / 0.70, 1)        # Poppins cap height is about 0.70 em
    html = f"""<!doctype html><meta charset="utf-8"><style>
      @font-face{{font-family:P;src:url('file://{font}') format('woff2');font-weight:600}}
      html,body{{margin:0;width:{width}px;height:{height}px;background:transparent}}
      .w{{display:flex;align-items:center;justify-content:center;width:100%;height:100%}}
      .t{{font-family:P;font-weight:600;font-size:{size}px;letter-spacing:{px_cap*0.155:.2f}px;
         background:{grad};
         -webkit-background-clip:text;background-clip:text;color:transparent;
         filter:{shadow};
         white-space:nowrap}}
    </style><div class="w"><span class="t">{text}</span></div>"""
    tmp = os.path.join(ROOT, '.cover-line.html')
    png = os.path.join(ROOT, '.cover-line.png')
    open(tmp, 'w', encoding='utf-8').write(html)
    pw = os.environ.get('PW') or 'playwright'
    shot = f"""const {{chromium}}=require('{pw}');
    (async()=>{{const b=await chromium.launch();
     const p=await b.newPage({{viewport:{{width:{width},height:{height}}},deviceScaleFactor:1}});
     await p.goto('file://{tmp}');await p.evaluate(()=>document.fonts.ready);await p.waitForTimeout(250);
     await p.screenshot({{path:'{png}',omitBackground:true}});await b.close();}})();"""
    subprocess.run(['node', '-e', shot], check=True, capture_output=True)
    out = Image.open(png).convert('RGBA').copy()
    os.remove(tmp); os.remove(png)
    return out


def build(cover, check=False):
    src = os.path.join(ROOT, cover['src'])
    img = Image.open(src).convert('RGB')
    w, h = img.size
    m = measure(cover['src'])
    print(f"  {cover['name']:6} source {w}x{h}  bottom line: "
          f"y {m['top']}..{m['bottom']} (cap {m['cap']}px), x {m['left']}..{m['right']}")
    if check:
        return
    band = cover['band'] or (m['top'] - 13, m['bottom'] + 13)
    above = cover.get('above') or (band[0] - 22, band[0])
    below = cover.get('below') or (band[1], band[1] + 22)
    cleaned = clear_band(img, band, above, below)

    scale = OUT_W / w
    big = cleaned.resize((OUT_W, OUT_H), Image.LANCZOS)
    big = big.filter(ImageFilter.UnsharpMask(radius=1.6, percent=48, threshold=3))

    cap = round((cover['cap'] or m['cap']) * scale)
    base = round((cover['baseline'] or m['baseline']) * scale)
    line = render_line(cover['text'], cap, OUT_W, round(cap * 3), cover.get('ink', 'book'))
    # the rendered line is vertically centred in its box, so sit that box's
    # middle on the old line's optical middle
    big.paste(line, (0, base - round(cap * 3 / 2) - round(cap * 0.5)), line)
    out = os.path.join(ROOT, cover['out'])
    big.save(out)
    print(f"         -> {cover['out']}  {OUT_W}x{OUT_H}  "
          f"{os.path.getsize(out)/1024:.0f} KB  {OUT_W/6:.0f} ppi at 6x9")


if __name__ == '__main__':
    check = '--check' in sys.argv
    for c in COVERS:
        if os.path.exists(os.path.join(ROOT, c['src'])):
            build(c, check)
